version: "{branch}-{build}"
image: Visual Studio 2015
configuration: Release
environment:
  QTDIR: C:\Qt\5.9\msvc2015
  PATH: '%PATH%;%QTDIR%\bin;'
  matrix:
  - {}
before_build:
- cmd: cmake .
build:
  project: qfm1000.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    set PATH=%PATH%;%QTDIR%\bin;

    C:\projects\qfm1000\src\eeprom\Release\testeeprom.exe
artifacts:
- path: src\Release\qfm1000.exe
  name: qfm1000.exe