language: cpp

os: osx
osx_image: xcode9.3
compiler: clang
before_install:
- brew update
install:
- brew install qt5
before_script:
- export QTDIR="/usr/local/opt/qt"
- export LDFLAGS="-L$QTDIR/lib:$LDFLAGS"
- export CPPFLAGS="-I$QTDIR/include:$CPPFLAGS"
- export PKG_CONFIG_PATH="$QTDIR/lib/pkgconfig:$PKG_CONFIG_PATH"
- export PATH="$QTDIR/bin:$PATH"

script:
- mkdir build
- cd build
- cmake ..
- make

after_script:
- cd build
- ctest
